### ISSUE TITLE
打包出来的dist目录下没有图片以及images目录

### ISSUE THREAD

**Issue by keandfan** [weijhfly/js-utils#1]
![image](https://user-images.githubusercontent.com/37890226/69594950-ea19e500-1038-11ea-872f-0d06a4194afb.png)
如标题
node版本12.13.0

**Comment by weijhfly** [comment]
代码就两三行，有可能是压缩图片插件与node版本不兼容，有空我再切换node版本试试

**Comment by weijhfly** [comment]
这边测试了node 12.13.0，以及当前最新版13.2.0，都没有发现打包不了图片问题，暂时不能确定问题了

**Comment by keandfan** [comment]
今天好像没问题了，可能是我这本地环境的问题。。稍后我就删除这个问题了。。谢谢
